Alpac495/Birdie_Buddy

- src/main/reactjs/package-lock.json
- src/main/reactjs/package.json
- src/main/reactjs/src/chatbot/ChatBot.js
- src/main/reactjs/src/chatbot/NCloudChatComponent.js
0712 저녁 commit
ncloud chat 채널 생성 및 채팅
> 0712 저녁 commit

- src/main/reactjs/src/hugi/Hugi.css
- src/main/reactjs/src/hugi/HugiList.js
> ssw 0712 commit

- src/main/reactjs/src/Home.js
- src/main/reactjs/src/chatbot/ChatBot.js
- src/main/reactjs/src/chatbot/NCloudChatComponent.js
0713 저녁 commit
ncloud chat 메세지 발송 시 중복 출력되는 문제 해결
> 0713 저녁 commit

- src/main/java/data/controller/JoinmemberController.java
- src/main/java/data/mapper/JoinmemberMapper.java
- src/main/java/data/service/JoinmemberService.java
- src/main/reactjs/src/Home.js
- src/main/reactjs/src/RouteMain.js
- src/main/reactjs/src/joining/JoinDetail.css
- src/main/reactjs/src/joining/JoinDetail.js
- src/main/reactjs/src/joining/JoinList.js
- src/main/reactjs/src/joining/JoinListMine.js
- src/main/resources/mapper/JoinmemberSql.xml
> 0719 pms lunch commit

- src/main/java/data/dto/JoinmemberDto.java
- src/main/reactjs/src/chatbot/ChatRoom.js
- src/main/reactjs/src/chatbot/NCloudChatRoomAdmin.js
- src/main/reactjs/src/chatbot/NCloudChatRoomList.js
- src/main/reactjs/src/friend/FriendDetail.js
- src/main/reactjs/src/joining/JoinAllList.js
- src/main/reactjs/src/joining/JoinDetail.js
- src/main/reactjs/src/joining/JoinList.css
- src/main/resources/mapper/JoinmemberSql.xml
0725 pms commit
조인 일부 수정 및 채팅 수정
> 0725 pms commit

- src/main/java/data/controller/ChatingController.java
- src/main/java/data/dto/ChatroomDto.java
- src/main/java/data/mapper/ChatingMapper.java
- src/main/java/data/service/ChatingService.java
- src/main/java/data/service/ChatingServiceInter.java
- src/main/reactjs/src/chatbot/ChatRoom.js
- src/main/reactjs/src/chatbot/NCloudChatRoomList.js
- src/main/reactjs/src/friend/Friend.js
- src/main/resources/mapper/ChatingSql.xml
pms 0725 저녁 커밋 chatroom dto 추가
> pms 0725 저녁 커밋 chatroom dto 추가

- src/main/reactjs/src/chatbot/ChatRoom.js
- src/main/reactjs/src/chatbot/NCloudChatRoomList.js
- src/main/reactjs/src/friend/Friend.js
> 0726 pms commit 채팅 관련 수정

- src/main/java/data/controller/MainController.java
- src/main/reactjs/src/app_effect/FriendSlider.js
- src/main/reactjs/src/chatbot/NCloudChatRoomList.js
- src/main/reactjs/src/friend/FriendRequest.js
- src/main/resources/mapper/FriendSql.xml
> pms 0726 commit

- src/main/java/data/controller/MainController.java
- src/main/java/data/dto/NoticeDto.java
- src/main/java/data/mapper/MainMapper.java
- src/main/reactjs/src/admin/NoticeForm.js
- src/main/reactjs/src/app_effect/FriendSlider.js
- src/main/reactjs/src/app_effect/Recommendslider.js
- src/main/reactjs/src/header/Header.css
- src/main/reactjs/src/header/Header.js
- src/main/resources/mapper/AdminSql.xml
- src/main/resources/mapper/MainSql.xml
> 0727 오후 커밋

- src/main/java/data/controller/AdminContoller.java
- src/main/java/data/controller/JoiningController.java
- src/main/java/data/mapper/AdminMapper.java
- src/main/java/data/mapper/JoiningMapper.java
- src/main/reactjs/src/admin/Blacklist.js
- src/main/reactjs/src/admin/UserList.css
- src/main/reactjs/src/admin/UserList.js
- src/main/reactjs/src/friend/Friend.css
- src/main/reactjs/src/friend/Friend.js
- src/main/reactjs/src/friend/FriendRequest.css
- src/main/reactjs/src/friend/FriendRequest.js
- src/main/reactjs/src/friend/FriendSearch.js
- src/main/reactjs/src/joining/JoinAllList.js
- src/main/resources/mapper/AdminSql.xml
- src/main/resources/mapper/JoiningSql.xml
> 0727 pms commit 무한스크롤 적용

- src/main/reactjs/package-lock.json
- src/main/reactjs/src/admin/Blacklist.js
- src/main/reactjs/src/admin/UserList.css
- src/main/reactjs/src/admin/UserList.js
- src/main/reactjs/src/chatbot/ChatRoom.css
- src/main/reactjs/src/chatbot/ChatRoom.js
- src/main/reactjs/src/friend/Friend.js
- src/main/reactjs/src/friend/FriendRequest.js
pms 0728 commit 채팅방 버튼 수정 및 리스트 출력페이지들 헤더 적용
> pms 0728 commit 채팅방 버튼 수정 및 리스트 출력페이지들 헤더 적용

- src/main/java/data/controller/AdminContoller.java
- src/main/reactjs/.env
- src/main/reactjs/package-lock.json
- src/main/reactjs/src/admin/NoticeDetail.css
- src/main/reactjs/src/admin/NoticeDetail.js
- src/main/reactjs/src/admin/NoticeForm.css
- src/main/reactjs/src/admin/NoticeForm.js
- src/main/reactjs/src/admin/NoticeList.css
- src/main/reactjs/src/admin/NoticeList.js
- src/main/reactjs/src/header/Header.css
- src/main/reactjs/src/header/Header.js
- src/main/resources/mapper/AdminSql.xml
노티스 리스트 css 거의 완
노티스 디테일 css
노티스 폼 css
노티스 수정 삭제?
> 0728 오후 커밋

- src/main/reactjs/package-lock.json
- src/main/reactjs/src/admin/UserList.css
- src/main/reactjs/src/admin/UserList.js
- src/main/reactjs/src/chatbot/NCloudChatRoomList.css
- src/main/reactjs/src/chatbot/NCloudChatRoomList.js
- src/main/reactjs/src/friend/Friend.css
- src/main/reactjs/src/friend/FriendRequest.css
- src/main/reactjs/src/mypage/MypageUpdateBgphoto.css
pms 0728 commit 채팅리스트 및 각종 버튼 수정
> pms 0728 commit 채팅리스트 및 각종 버튼 수정

- src/main/reactjs/package-lock.json
- src/main/reactjs/src/admin/NoticeDetail.css
- src/main/reactjs/src/admin/NoticeDetail.js
- src/main/reactjs/src/admin/NoticeForm.css
- src/main/reactjs/src/admin/NoticeForm.js
- src/main/reactjs/src/admin/NoticeList.css
- src/main/reactjs/src/admin/NoticeList.js
- src/main/reactjs/src/app_effect/BannerSlider.js
- src/main/reactjs/src/app_effect/FriendSlider.js
노티스 폼 css
노티스 수정 삭제
노티스 리스트 페이징
> 0729 오전 커밋

- src/main/resources/mapper/AdminSql.xml
> 0729 pms commit 전체사용자 신고출력 수정

- src/main/reactjs/package-lock.json
- src/main/reactjs/src/Main.js
- src/main/reactjs/src/hugi/HugiDetail.js
- src/main/reactjs/src/hugi/HugiRowList.js
- src/main/reactjs/src/hugi/MyHugiRowList.js
ssw commit hugilist api앞에 안붙은거 수정
> ssw commit hugilist api앞에 안붙은거 수정

- src/main/reactjs/src/Main.js
- src/main/reactjs/src/header/Header.js
- src/main/reactjs/src/yangdo/YangdoList.css
- src/main/reactjs/src/yangdo/YangdoList.js
> ssw commit!!

- src/main/reactjs/src/admin/Blacklist.js
- src/main/reactjs/src/admin/UserList.js
- src/main/reactjs/src/app_effect/Recommendslider.js
- src/main/reactjs/src/friend/FriendSearch.js
- src/main/reactjs/src/hugi/HugiDetail.js
- src/main/reactjs/src/hugi/HugiList.js
- src/main/reactjs/src/hugi/HugiRowList.js
- src/main/reactjs/src/hugi/MyHugiList.js
- src/main/reactjs/src/hugi/MyHugiRowList.js
- src/main/reactjs/src/ranking/AllRank.js
- src/main/reactjs/src/ranking/MyRank.js
> ssw commit!

- src/main/reactjs/src/hugi/HugiDetail.js
> ssw commit 집가기전 커밋

- src/main/reactjs/src/hugi/HugiDetail.js
- src/main/reactjs/src/hugi/HugiRowList.js
- src/main/reactjs/src/hugi/MyHugiRowList.js
> ssw commit! 댓글 길이 제한 늘림 
